name: keycloak-x-heroku
region: syd1
services:
  - name: keycloak
    github:
      repo: bikramkgupta/keycloak.x-heroku
      branch: app_platform
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 30
      success_threshold: 1
      failure_threshold: 5
    envs:
      - key: KC_BOOTSTRAP_ADMIN_USERNAME
        scope: RUN_TIME
        type: SECRET
        value: admin
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: wJ5SqF4gYg7yzr8evMD3lEpl6d4=
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_URL}
      - key: PORT
        scope: RUN_TIME
        type: GENERAL
        value: "8080"